admin.username=admin
admin.password=admin123

db.primary.url=jdbc:postgresql://localhost:5432/first_db
db.primary.username=postgres
db.primary.password=postgres

db.replica.url=jdbc:postgresql://localhost:5432/first_db_replica
db.replica.username=postgres
db.replica.password=postgres